version: '3.4'

services:
  miniproductcrud:
    image: ${DOCKER_REGISTRY-}miniproductcrud
    build:
      context: .
      dockerfile: MiniProductCRUD/Dockerfile
  
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
        - 3306:3306
        - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: D7gwf2421
      MYSQL_DATABASE: 'db'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080